# Generated by Django 5.1.5 on 2025-02-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
