# Generated by Django 5.1.5 on 2025-02-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0004_posts_like_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='like_count',
            new_name='liked_users',
        ),
    ]
